### ISSUE TITLE
memory not being deallocated.

### ISSUE THREAD

**Issue by ahoang** [sozorogami/SOZOChromoplast#4]
We are using this library on a lot of our views and noticed a huge memory leak coming from the library. After investigation we found in SOZOBitmapDataGenerator.m:44, memory is being allocated but never released.

**Comment by sozorogami** [comment]
Hi @ahoang 

Thanks so much for bringing this to my attention, and sorry for the trouble it caused you.

I've made PR for this. Can you confirm that it fixes things on your side?

**Comment by sozorogami** [comment]
Fixed in v0.0.3
